apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netmux-tokens
  namespace: netmux
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: local-path

