// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: misc/proto/proxy.proto

package cluster

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ClusterClient is the client API for Cluster service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClusterClient interface {
	Ver(ctx context.Context, in *Noop, opts ...grpc.CallOption) (*Noop, error)
	Proxy(ctx context.Context, opts ...grpc.CallOption) (Cluster_ProxyClient, error)
	ReverseProxyListen(ctx context.Context, opts ...grpc.CallOption) (Cluster_ReverseProxyListenClient, error)
	ReverseProxyWork(ctx context.Context, opts ...grpc.CallOption) (Cluster_ReverseProxyWorkClient, error)
	Ping(ctx context.Context, in *StringMsg, opts ...grpc.CallOption) (*StringMsg, error)
	PortScan(ctx context.Context, in *StringMsg, opts ...grpc.CallOption) (*StringMsg, error)
	Nc(ctx context.Context, in *StringMsg, opts ...grpc.CallOption) (*StringMsg, error)
	SpeedTest(ctx context.Context, in *StringMsg, opts ...grpc.CallOption) (*BytesMsg, error)
	KeepAlive(ctx context.Context, in *Noop, opts ...grpc.CallOption) (Cluster_KeepAliveClient, error)
	GetConfigs(ctx context.Context, in *Noop, opts ...grpc.CallOption) (*Bridges, error)
	StreamConfig(ctx context.Context, in *Noop, opts ...grpc.CallOption) (Cluster_StreamConfigClient, error)
	Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*StringMsg, error)
	Logout(ctx context.Context, in *StringMsg, opts ...grpc.CallOption) (*Noop, error)
}

type clusterClient struct {
	cc grpc.ClientConnInterface
}

func NewClusterClient(cc grpc.ClientConnInterface) ClusterClient {
	return &clusterClient{cc}
}

func (c *clusterClient) Ver(ctx context.Context, in *Noop, opts ...grpc.CallOption) (*Noop, error) {
	out := new(Noop)
	err := c.cc.Invoke(ctx, "/cluster.Cluster/Ver", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterClient) Proxy(ctx context.Context, opts ...grpc.CallOption) (Cluster_ProxyClient, error) {
	stream, err := c.cc.NewStream(ctx, &Cluster_ServiceDesc.Streams[0], "/cluster.Cluster/Proxy", opts...)
	if err != nil {
		return nil, err
	}
	x := &clusterProxyClient{stream}
	return x, nil
}

type Cluster_ProxyClient interface {
	Send(*ConnOut) error
	Recv() (*ConnIn, error)
	grpc.ClientStream
}

type clusterProxyClient struct {
	grpc.ClientStream
}

func (x *clusterProxyClient) Send(m *ConnOut) error {
	return x.ClientStream.SendMsg(m)
}

func (x *clusterProxyClient) Recv() (*ConnIn, error) {
	m := new(ConnIn)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *clusterClient) ReverseProxyListen(ctx context.Context, opts ...grpc.CallOption) (Cluster_ReverseProxyListenClient, error) {
	stream, err := c.cc.NewStream(ctx, &Cluster_ServiceDesc.Streams[1], "/cluster.Cluster/ReverseProxyListen", opts...)
	if err != nil {
		return nil, err
	}
	x := &proxyReverseProxyListenClient{stream}
	return x, nil
}

type Cluster_ReverseProxyListenClient interface {
	Send(*ConnOut) error
	Recv() (*RevProxyRequest, error)
	grpc.ClientStream
}

type proxyReverseProxyListenClient struct {
	grpc.ClientStream
}

func (x *proxyReverseProxyListenClient) Send(m *ConnOut) error {
	return x.ClientStream.SendMsg(m)
}

func (x *proxyReverseProxyListenClient) Recv() (*RevProxyRequest, error) {
	m := new(RevProxyRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *clusterClient) ReverseProxyWork(ctx context.Context, opts ...grpc.CallOption) (Cluster_ReverseProxyWorkClient, error) {
	stream, err := c.cc.NewStream(ctx, &Cluster_ServiceDesc.Streams[2], "/cluster.Cluster/ReverseProxyWork", opts...)
	if err != nil {
		return nil, err
	}
	x := &proxyReverseProxyWorkClient{stream}
	return x, nil
}

type Cluster_ReverseProxyWorkClient interface {
	Send(*RevProxyConnIn) error
	Recv() (*RevProxyConnOut, error)
	grpc.ClientStream
}

type proxyReverseProxyWorkClient struct {
	grpc.ClientStream
}

func (x *proxyReverseProxyWorkClient) Send(m *RevProxyConnIn) error {
	return x.ClientStream.SendMsg(m)
}

func (x *proxyReverseProxyWorkClient) Recv() (*RevProxyConnOut, error) {
	m := new(RevProxyConnOut)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *clusterClient) Ping(ctx context.Context, in *StringMsg, opts ...grpc.CallOption) (*StringMsg, error) {
	out := new(StringMsg)
	err := c.cc.Invoke(ctx, "/cluster.Cluster/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterClient) PortScan(ctx context.Context, in *StringMsg, opts ...grpc.CallOption) (*StringMsg, error) {
	out := new(StringMsg)
	err := c.cc.Invoke(ctx, "/cluster.Cluster/PortScan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterClient) Nc(ctx context.Context, in *StringMsg, opts ...grpc.CallOption) (*StringMsg, error) {
	out := new(StringMsg)
	err := c.cc.Invoke(ctx, "/cluster.Cluster/Nc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterClient) SpeedTest(ctx context.Context, in *StringMsg, opts ...grpc.CallOption) (*BytesMsg, error) {
	out := new(BytesMsg)
	err := c.cc.Invoke(ctx, "/cluster.Cluster/SpeedTest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterClient) KeepAlive(ctx context.Context, in *Noop, opts ...grpc.CallOption) (Cluster_KeepAliveClient, error) {
	stream, err := c.cc.NewStream(ctx, &Cluster_ServiceDesc.Streams[3], "/cluster.Cluster/KeepAlive", opts...)
	if err != nil {
		return nil, err
	}
	x := &proxyKeepAliveClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Cluster_KeepAliveClient interface {
	Recv() (*StringMsg, error)
	grpc.ClientStream
}

type proxyKeepAliveClient struct {
	grpc.ClientStream
}

func (x *proxyKeepAliveClient) Recv() (*StringMsg, error) {
	m := new(StringMsg)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *clusterClient) GetConfigs(ctx context.Context, in *Noop, opts ...grpc.CallOption) (*Bridges, error) {
	out := new(Bridges)
	err := c.cc.Invoke(ctx, "/cluster.Cluster/GetConfigs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterClient) StreamConfig(ctx context.Context, in *Noop, opts ...grpc.CallOption) (Cluster_StreamConfigClient, error) {
	stream, err := c.cc.NewStream(ctx, &Cluster_ServiceDesc.Streams[4], "/cluster.Cluster/StreamConfig", opts...)
	if err != nil {
		return nil, err
	}
	x := &ProxyStreamConfigClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Cluster_StreamConfigClient interface {
	Recv() (*Bridges, error)
	grpc.ClientStream
}

type ProxyStreamConfigClient struct {
	grpc.ClientStream
}

func (x *ProxyStreamConfigClient) Recv() (*Bridges, error) {
	m := new(Bridges)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *clusterClient) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*StringMsg, error) {
	out := new(StringMsg)
	err := c.cc.Invoke(ctx, "/cluster.Cluster/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterClient) Logout(ctx context.Context, in *StringMsg, opts ...grpc.CallOption) (*Noop, error) {
	out := new(Noop)
	err := c.cc.Invoke(ctx, "/cluster.Cluster/Logout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProxyServer is the server API for Proxy service.
// All implementations must embed UnimplementedProxyServer
// for forward compatibility
type ProxyServer interface {
	Ver(context.Context, *Noop) (*Noop, error)
	Proxy(Cluster_ProxyServer) error
	ReverseProxyListen(Cluster_ReverseProxyListenServer) error
	ReverseProxyWork(Cluster_ReverseProxyWorkServer) error
	Ping(context.Context, *StringMsg) (*StringMsg, error)
	PortScan(context.Context, *StringMsg) (*StringMsg, error)
	Nc(context.Context, *StringMsg) (*StringMsg, error)
	SpeedTest(context.Context, *StringMsg) (*BytesMsg, error)
	KeepAlive(*Noop, Cluster_KeepAliveServer) error
	GetConfigs(context.Context, *Noop) (*Bridges, error)
	StreamConfig(*Noop, Cluster_StreamConfigServer) error
	Login(context.Context, *LoginReq) (*StringMsg, error)
	Logout(context.Context, *StringMsg) (*Noop, error)
	mustEmbedUnimplementedProxyServer()
}

// UnimplementedProxyServer must be embedded to have forward compatible implementations.
type UnimplementedProxyServer struct {
}

func (UnimplementedProxyServer) Ver(context.Context, *Noop) (*Noop, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ver not implemented")
}
func (UnimplementedProxyServer) Proxy(Cluster_ProxyServer) error {
	return status.Errorf(codes.Unimplemented, "method Proxy not implemented")
}
func (UnimplementedProxyServer) ReverseProxyListen(Cluster_ReverseProxyListenServer) error {
	return status.Errorf(codes.Unimplemented, "method ReverseProxyListen not implemented")
}
func (UnimplementedProxyServer) ReverseProxyWork(Cluster_ReverseProxyWorkServer) error {
	return status.Errorf(codes.Unimplemented, "method ReverseProxyWork not implemented")
}
func (UnimplementedProxyServer) Ping(context.Context, *StringMsg) (*StringMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedProxyServer) PortScan(context.Context, *StringMsg) (*StringMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PortScan not implemented")
}
func (UnimplementedProxyServer) Nc(context.Context, *StringMsg) (*StringMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Nc not implemented")
}
func (UnimplementedProxyServer) SpeedTest(context.Context, *StringMsg) (*BytesMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SpeedTest not implemented")
}
func (UnimplementedProxyServer) KeepAlive(*Noop, Cluster_KeepAliveServer) error {
	return status.Errorf(codes.Unimplemented, "method KeepAlive not implemented")
}
func (UnimplementedProxyServer) GetConfigs(context.Context, *Noop) (*Bridges, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfigs not implemented")
}
func (UnimplementedProxyServer) StreamConfig(*Noop, Cluster_StreamConfigServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamConfig not implemented")
}
func (UnimplementedProxyServer) Login(context.Context, *LoginReq) (*StringMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedProxyServer) Logout(context.Context, *StringMsg) (*Noop, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedProxyServer) mustEmbedUnimplementedProxyServer() {}

// UnsafeProxyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProxyServer will
// result in compilation errors.
type UnsafeProxyServer interface {
	mustEmbedUnimplementedProxyServer()
}

func RegisterProxyServer(s grpc.ServiceRegistrar, srv ProxyServer) {
	s.RegisterService(&Cluster_ServiceDesc, srv)
}

func _Cluster_Ver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Noop)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServer).Ver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cluster.Cluster/Ver",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServer).Ver(ctx, req.(*Noop))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cluster_Cluster_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProxyServer).Proxy(&ProxyProxyServer{stream})
}

type Cluster_ProxyServer interface {
	Send(*ConnIn) error
	Recv() (*ConnOut, error)
	grpc.ServerStream
}

type ProxyProxyServer struct {
	grpc.ServerStream
}

func (x *ProxyProxyServer) Send(m *ConnIn) error {
	return x.ServerStream.SendMsg(m)
}

func (x *ProxyProxyServer) Recv() (*ConnOut, error) {
	m := new(ConnOut)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Cluster_ReverseProxyListen_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProxyServer).ReverseProxyListen(&ProxyReverseProxyListenServer{stream})
}

type Cluster_ReverseProxyListenServer interface {
	Send(*RevProxyRequest) error
	Recv() (*ConnOut, error)
	grpc.ServerStream
}

type ProxyReverseProxyListenServer struct {
	grpc.ServerStream
}

func (x *ProxyReverseProxyListenServer) Send(m *RevProxyRequest) error {
	return x.ServerStream.SendMsg(m)
}

func (x *ProxyReverseProxyListenServer) Recv() (*ConnOut, error) {
	m := new(ConnOut)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Cluster_ReverseProxyWork_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProxyServer).ReverseProxyWork(&proxyReverseProxyWorkServer{stream})
}

type Cluster_ReverseProxyWorkServer interface {
	Send(*RevProxyConnOut) error
	Recv() (*RevProxyConnIn, error)
	grpc.ServerStream
}

type proxyReverseProxyWorkServer struct {
	grpc.ServerStream
}

func (x *proxyReverseProxyWorkServer) Send(m *RevProxyConnOut) error {
	return x.ServerStream.SendMsg(m)
}

func (x *proxyReverseProxyWorkServer) Recv() (*RevProxyConnIn, error) {
	m := new(RevProxyConnIn)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Cluster_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cluster.Cluster/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServer).Ping(ctx, req.(*StringMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cluster_PortScan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServer).PortScan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cluster.Cluster/PortScan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServer).PortScan(ctx, req.(*StringMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cluster_Nc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServer).Nc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cluster.Cluster/Nc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServer).Nc(ctx, req.(*StringMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cluster_SpeedTest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServer).SpeedTest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cluster.Cluster/SpeedTest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServer).SpeedTest(ctx, req.(*StringMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cluster_KeepAlive_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Noop)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProxyServer).KeepAlive(m, &ProxyKeepAliveServer{stream})
}

type Cluster_KeepAliveServer interface {
	Send(*StringMsg) error
	grpc.ServerStream
}

type ProxyKeepAliveServer struct {
	grpc.ServerStream
}

func (x *ProxyKeepAliveServer) Send(m *StringMsg) error {
	return x.ServerStream.SendMsg(m)
}

func _Cluster_GetConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Noop)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServer).GetConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cluster.Cluster/GetConfigs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServer).GetConfigs(ctx, req.(*Noop))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cluster_StreamConfig_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Noop)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProxyServer).StreamConfig(m, &ProxyStreamConfigServer{stream})
}

type Cluster_StreamConfigServer interface {
	Send(*Bridges) error
	grpc.ServerStream
}

type ProxyStreamConfigServer struct {
	grpc.ServerStream
}

func (x *ProxyStreamConfigServer) Send(m *Bridges) error {
	return x.ServerStream.SendMsg(m)
}

func _Cluster_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cluster.Cluster/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServer).Login(ctx, req.(*LoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cluster_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cluster.Cluster/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServer).Logout(ctx, req.(*StringMsg))
	}
	return interceptor(ctx, in, info, handler)
}

// Cluster_ServiceDesc is the grpc.ServiceDesc for Proxy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Cluster_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cluster.Cluster",
	HandlerType: (*ProxyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ver",
			Handler:    _Cluster_Ver_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _Cluster_Ping_Handler,
		},
		{
			MethodName: "PortScan",
			Handler:    _Cluster_PortScan_Handler,
		},
		{
			MethodName: "Nc",
			Handler:    _Cluster_Nc_Handler,
		},
		{
			MethodName: "SpeedTest",
			Handler:    _Cluster_SpeedTest_Handler,
		},
		{
			MethodName: "GetConfigs",
			Handler:    _Cluster_GetConfigs_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Cluster_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _Cluster_Logout_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Proxy",
			Handler:       _Cluster_Cluster_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ReverseProxyListen",
			Handler:       _Cluster_ReverseProxyListen_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ReverseProxyWork",
			Handler:       _Cluster_ReverseProxyWork_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "KeepAlive",
			Handler:       _Cluster_KeepAlive_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamConfig",
			Handler:       _Cluster_StreamConfig_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "misc/proto/service_server.proto",
}
