// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: misc/proto/service_server.proto

package server

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bridge struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Localaddr    string `protobuf:"bytes,2,opt,name=localaddr,proto3" json:"localaddr,omitempty"`
	Localport    string `protobuf:"bytes,3,opt,name=localport,proto3" json:"localport,omitempty"`
	Remoteaddr   string `protobuf:"bytes,4,opt,name=remoteaddr,proto3" json:"remoteaddr,omitempty"`
	Remoteport   string `protobuf:"bytes,5,opt,name=remoteport,proto3" json:"remoteport,omitempty"`
	Direction    string `protobuf:"bytes,6,opt,name=direction,proto3" json:"direction,omitempty"`
	Proto        string `protobuf:"bytes,7,opt,name=proto,proto3" json:"proto,omitempty"`
	Auto         bool   `protobuf:"varint,8,opt,name=auto,proto3" json:"auto,omitempty"`
	K8Snamespace string `protobuf:"bytes,9,opt,name=k8snamespace,proto3" json:"k8snamespace,omitempty"`
	K8Sname      string `protobuf:"bytes,10,opt,name=k8sname,proto3" json:"k8sname,omitempty"`
	K8Skind      string `protobuf:"bytes,11,opt,name=k8skind,proto3" json:"k8skind,omitempty"`
	Bridgeop     string `protobuf:"bytes,12,opt,name=bridgeop,proto3" json:"bridgeop,omitempty"`
}

func (x *Bridge) Reset() {
	*x = Bridge{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_service_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bridge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bridge) ProtoMessage() {}

func (x *Bridge) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_service_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bridge.ProtoReflect.Descriptor instead.
func (*Bridge) Descriptor() ([]byte, []int) {
	return file_misc_proto_service_server_proto_rawDescGZIP(), []int{0}
}

func (x *Bridge) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Bridge) GetLocaladdr() string {
	if x != nil {
		return x.Localaddr
	}
	return ""
}

func (x *Bridge) GetLocalport() string {
	if x != nil {
		return x.Localport
	}
	return ""
}

func (x *Bridge) GetRemoteaddr() string {
	if x != nil {
		return x.Remoteaddr
	}
	return ""
}

func (x *Bridge) GetRemoteport() string {
	if x != nil {
		return x.Remoteport
	}
	return ""
}

func (x *Bridge) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *Bridge) GetProto() string {
	if x != nil {
		return x.Proto
	}
	return ""
}

func (x *Bridge) GetAuto() bool {
	if x != nil {
		return x.Auto
	}
	return false
}

func (x *Bridge) GetK8Snamespace() string {
	if x != nil {
		return x.K8Snamespace
	}
	return ""
}

func (x *Bridge) GetK8Sname() string {
	if x != nil {
		return x.K8Sname
	}
	return ""
}

func (x *Bridge) GetK8Skind() string {
	if x != nil {
		return x.K8Skind
	}
	return ""
}

func (x *Bridge) GetBridgeop() string {
	if x != nil {
		return x.Bridgeop
	}
	return ""
}

type Bridges struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Eps []*Bridge `protobuf:"bytes,1,rep,name=eps,proto3" json:"eps,omitempty"`
}

func (x *Bridges) Reset() {
	*x = Bridges{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_service_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bridges) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bridges) ProtoMessage() {}

func (x *Bridges) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_service_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bridges.ProtoReflect.Descriptor instead.
func (*Bridges) Descriptor() ([]byte, []int) {
	return file_misc_proto_service_server_proto_rawDescGZIP(), []int{1}
}

func (x *Bridges) GetEps() []*Bridge {
	if x != nil {
		return x.Eps
	}
	return nil
}

type Noop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Err string `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *Noop) Reset() {
	*x = Noop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_service_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Noop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Noop) ProtoMessage() {}

func (x *Noop) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_service_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Noop.ProtoReflect.Descriptor instead.
func (*Noop) Descriptor() ([]byte, []int) {
	return file_misc_proto_service_server_proto_rawDescGZIP(), []int{2}
}

func (x *Noop) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *Noop) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type LoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Pass string `protobuf:"bytes,2,opt,name=pass,proto3" json:"pass,omitempty"`
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_service_server_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_service_server_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_misc_proto_service_server_proto_rawDescGZIP(), []int{3}
}

func (x *LoginReq) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *LoginReq) GetPass() string {
	if x != nil {
		return x.Pass
	}
	return ""
}

type StringMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *StringMsg) Reset() {
	*x = StringMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_service_server_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringMsg) ProtoMessage() {}

func (x *StringMsg) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_service_server_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringMsg.ProtoReflect.Descriptor instead.
func (*StringMsg) Descriptor() ([]byte, []int) {
	return file_misc_proto_service_server_proto_rawDescGZIP(), []int{4}
}

func (x *StringMsg) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type BytesMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg []byte `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *BytesMsg) Reset() {
	*x = BytesMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_service_server_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BytesMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BytesMsg) ProtoMessage() {}

func (x *BytesMsg) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_service_server_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BytesMsg.ProtoReflect.Descriptor instead.
func (*BytesMsg) Descriptor() ([]byte, []int) {
	return file_misc_proto_service_server_proto_rawDescGZIP(), []int{5}
}

func (x *BytesMsg) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

type PingReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ctx string `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	Ep  string `protobuf:"bytes,2,opt,name=ep,proto3" json:"ep,omitempty"`
}

func (x *PingReq) Reset() {
	*x = PingReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_service_server_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReq) ProtoMessage() {}

func (x *PingReq) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_service_server_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReq.ProtoReflect.Descriptor instead.
func (*PingReq) Descriptor() ([]byte, []int) {
	return file_misc_proto_service_server_proto_rawDescGZIP(), []int{6}
}

func (x *PingReq) GetCtx() string {
	if x != nil {
		return x.Ctx
	}
	return ""
}

func (x *PingReq) GetEp() string {
	if x != nil {
		return x.Ep
	}
	return ""
}

type PortScanReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ctx string `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	Ep  string `protobuf:"bytes,2,opt,name=ep,proto3" json:"ep,omitempty"`
}

func (x *PortScanReq) Reset() {
	*x = PortScanReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_service_server_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PortScanReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortScanReq) ProtoMessage() {}

func (x *PortScanReq) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_service_server_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortScanReq.ProtoReflect.Descriptor instead.
func (*PortScanReq) Descriptor() ([]byte, []int) {
	return file_misc_proto_service_server_proto_rawDescGZIP(), []int{7}
}

func (x *PortScanReq) GetCtx() string {
	if x != nil {
		return x.Ctx
	}
	return ""
}

func (x *PortScanReq) GetEp() string {
	if x != nil {
		return x.Ep
	}
	return ""
}

type ConnOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bridge *Bridge `protobuf:"bytes,1,opt,name=bridge,proto3,oneof" json:"bridge,omitempty"`
	Pl     []byte  `protobuf:"bytes,2,opt,name=pl,proto3" json:"pl,omitempty"`
}

func (x *ConnOut) Reset() {
	*x = ConnOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_service_server_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnOut) ProtoMessage() {}

func (x *ConnOut) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_service_server_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnOut.ProtoReflect.Descriptor instead.
func (*ConnOut) Descriptor() ([]byte, []int) {
	return file_misc_proto_service_server_proto_rawDescGZIP(), []int{8}
}

func (x *ConnOut) GetBridge() *Bridge {
	if x != nil {
		return x.Bridge
	}
	return nil
}

func (x *ConnOut) GetPl() []byte {
	if x != nil {
		return x.Pl
	}
	return nil
}

type ConnIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pl  []byte `protobuf:"bytes,1,opt,name=pl,proto3" json:"pl,omitempty"`
	Err string `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *ConnIn) Reset() {
	*x = ConnIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_service_server_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnIn) ProtoMessage() {}

func (x *ConnIn) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_service_server_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnIn.ProtoReflect.Descriptor instead.
func (*ConnIn) Descriptor() ([]byte, []int) {
	return file_misc_proto_service_server_proto_rawDescGZIP(), []int{9}
}

func (x *ConnIn) GetPl() []byte {
	if x != nil {
		return x.Pl
	}
	return nil
}

func (x *ConnIn) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type RevProxyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConnId string `protobuf:"bytes,1,opt,name=connId,proto3" json:"connId,omitempty"`
}

func (x *RevProxyRequest) Reset() {
	*x = RevProxyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_service_server_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RevProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevProxyRequest) ProtoMessage() {}

func (x *RevProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_service_server_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevProxyRequest.ProtoReflect.Descriptor instead.
func (*RevProxyRequest) Descriptor() ([]byte, []int) {
	return file_misc_proto_service_server_proto_rawDescGZIP(), []int{10}
}

func (x *RevProxyRequest) GetConnId() string {
	if x != nil {
		return x.ConnId
	}
	return ""
}

type RevProxyConnIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConnId string `protobuf:"bytes,1,opt,name=connId,proto3" json:"connId,omitempty"`
	Pl     []byte `protobuf:"bytes,2,opt,name=pl,proto3" json:"pl,omitempty"`
}

func (x *RevProxyConnIn) Reset() {
	*x = RevProxyConnIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_service_server_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RevProxyConnIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevProxyConnIn) ProtoMessage() {}

func (x *RevProxyConnIn) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_service_server_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevProxyConnIn.ProtoReflect.Descriptor instead.
func (*RevProxyConnIn) Descriptor() ([]byte, []int) {
	return file_misc_proto_service_server_proto_rawDescGZIP(), []int{11}
}

func (x *RevProxyConnIn) GetConnId() string {
	if x != nil {
		return x.ConnId
	}
	return ""
}

func (x *RevProxyConnIn) GetPl() []byte {
	if x != nil {
		return x.Pl
	}
	return nil
}

type RevProxyConnOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pl  []byte `protobuf:"bytes,1,opt,name=pl,proto3" json:"pl,omitempty"`
	Err string `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *RevProxyConnOut) Reset() {
	*x = RevProxyConnOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_service_server_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RevProxyConnOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevProxyConnOut) ProtoMessage() {}

func (x *RevProxyConnOut) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_service_server_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevProxyConnOut.ProtoReflect.Descriptor instead.
func (*RevProxyConnOut) Descriptor() ([]byte, []int) {
	return file_misc_proto_service_server_proto_rawDescGZIP(), []int{12}
}

func (x *RevProxyConnOut) GetPl() []byte {
	if x != nil {
		return x.Pl
	}
	return nil
}

func (x *RevProxyConnOut) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

var File_misc_proto_service_server_proto protoreflect.FileDescriptor

var file_misc_proto_service_server_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x6d, 0x69, 0x73, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x22, 0xd4, 0x02, 0x0a, 0x06, 0x42, 0x72, 0x69,
	0x64, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x63, 0x61, 0x6c,
	0x61, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x6f, 0x63, 0x61,
	0x6c, 0x61, 0x64, 0x64, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x70, 0x6f,
	0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x70,
	0x6f, 0x72, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x61, 0x64, 0x64,
	0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x61,
	0x64, 0x64, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x75, 0x74, 0x6f, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x61, 0x75, 0x74, 0x6f, 0x12, 0x22, 0x0a, 0x0c, 0x6b,
	0x38, 0x73, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x6b, 0x38, 0x73, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x6b, 0x38, 0x73, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6b, 0x38, 0x73, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6b, 0x38, 0x73,
	0x6b, 0x69, 0x6e, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6b, 0x38, 0x73, 0x6b,
	0x69, 0x6e, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x6f, 0x70, 0x18,
	0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x6f, 0x70, 0x22,
	0x2a, 0x0a, 0x07, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x73, 0x12, 0x1f, 0x0a, 0x03, 0x65, 0x70,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e,
	0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x52, 0x03, 0x65, 0x70, 0x73, 0x22, 0x2a, 0x0a, 0x04, 0x4e,
	0x6f, 0x6f, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x22, 0x32, 0x0a, 0x08, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x73, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x73, 0x73, 0x22, 0x1d, 0x0a, 0x09, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x4d, 0x73, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x1c, 0x0a, 0x08, 0x42, 0x79,
	0x74, 0x65, 0x73, 0x4d, 0x73, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x2b, 0x0a, 0x07, 0x50, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x74, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x63, 0x74, 0x78, 0x12, 0x0e, 0x0a, 0x02, 0x65, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x65, 0x70, 0x22, 0x2f, 0x0a, 0x0b, 0x50, 0x6f, 0x72, 0x74, 0x53, 0x63, 0x61,
	0x6e, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x74, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x63, 0x74, 0x78, 0x12, 0x0e, 0x0a, 0x02, 0x65, 0x70, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x65, 0x70, 0x22, 0x50, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x6e, 0x4f, 0x75,
	0x74, 0x12, 0x2a, 0x0a, 0x06, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65,
	0x48, 0x00, 0x52, 0x06, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x88, 0x01, 0x01, 0x12, 0x0e, 0x0a,
	0x02, 0x70, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x70, 0x6c, 0x42, 0x09, 0x0a,
	0x07, 0x5f, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x22, 0x2a, 0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x6e,
	0x49, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x70, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02,
	0x70, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x65, 0x72, 0x72, 0x22, 0x29, 0x0a, 0x0f, 0x52, 0x65, 0x76, 0x50, 0x72, 0x6f, 0x78, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x6e, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x6e, 0x49, 0x64, 0x22,
	0x38, 0x0a, 0x0e, 0x52, 0x65, 0x76, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x43, 0x6f, 0x6e, 0x6e, 0x49,
	0x6e, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x6e, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x70, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x70, 0x6c, 0x22, 0x33, 0x0a, 0x0f, 0x52, 0x65, 0x76,
	0x50, 0x72, 0x6f, 0x78, 0x79, 0x43, 0x6f, 0x6e, 0x6e, 0x4f, 0x75, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x70, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x70, 0x6c, 0x12, 0x10, 0x0a, 0x03,
	0x65, 0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x32, 0x8c,
	0x05, 0x0a, 0x07, 0x4e, 0x58, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x12, 0x21, 0x0a, 0x03, 0x56, 0x65,
	0x72, 0x12, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x4e, 0x6f, 0x6f, 0x70, 0x1a, 0x0b,
	0x2e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x4e, 0x6f, 0x6f, 0x70, 0x22, 0x00, 0x12, 0x2c, 0x0a,
	0x05, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x12, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x43,
	0x6f, 0x6e, 0x6e, 0x4f, 0x75, 0x74, 0x1a, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x43,
	0x6f, 0x6e, 0x6e, 0x49, 0x6e, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x42, 0x0a, 0x12, 0x52,
	0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x65,
	0x6e, 0x12, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x4f, 0x75,
	0x74, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x52, 0x65, 0x76, 0x50, 0x72, 0x6f,
	0x78, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12,
	0x47, 0x0a, 0x10, 0x52, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x57,
	0x6f, 0x72, 0x6b, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x52, 0x65, 0x76, 0x50,
	0x72, 0x6f, 0x78, 0x79, 0x43, 0x6f, 0x6e, 0x6e, 0x49, 0x6e, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f,
	0x78, 0x79, 0x2e, 0x52, 0x65, 0x76, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x43, 0x6f, 0x6e, 0x6e, 0x4f,
	0x75, 0x74, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x2c, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67,
	0x12, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x4d,
	0x73, 0x67, 0x1a, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x4d, 0x73, 0x67, 0x22, 0x00, 0x12, 0x30, 0x0a, 0x08, 0x50, 0x6f, 0x72, 0x74, 0x53, 0x63,
	0x61, 0x6e, 0x12, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x4d, 0x73, 0x67, 0x1a, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x4d, 0x73, 0x67, 0x22, 0x00, 0x12, 0x2a, 0x0a, 0x02, 0x4e, 0x63, 0x12, 0x10,
	0x2e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x4d, 0x73, 0x67,
	0x1a, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x4d,
	0x73, 0x67, 0x22, 0x00, 0x12, 0x30, 0x0a, 0x09, 0x53, 0x70, 0x65, 0x65, 0x64, 0x54, 0x65, 0x73,
	0x74, 0x12, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x4d, 0x73, 0x67, 0x1a, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x42, 0x79, 0x74, 0x65,
	0x73, 0x4d, 0x73, 0x67, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x09, 0x4b, 0x65, 0x65, 0x70, 0x41, 0x6c,
	0x69, 0x76, 0x65, 0x12, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x4e, 0x6f, 0x6f, 0x70,
	0x1a, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x4d,
	0x73, 0x67, 0x22, 0x00, 0x30, 0x01, 0x12, 0x2b, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x73, 0x12, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x4e, 0x6f, 0x6f,
	0x70, 0x1a, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65,
	0x73, 0x22, 0x00, 0x12, 0x2f, 0x0a, 0x0c, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x12, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x4e, 0x6f, 0x6f, 0x70,
	0x1a, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x73,
	0x22, 0x00, 0x30, 0x01, 0x12, 0x2c, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x0f, 0x2e,
	0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x10,
	0x2e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x4d, 0x73, 0x67,
	0x22, 0x00, 0x12, 0x29, 0x0a, 0x06, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x12, 0x10, 0x2e, 0x70,
	0x72, 0x6f, 0x78, 0x79, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x4d, 0x73, 0x67, 0x1a, 0x0b,
	0x2e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x4e, 0x6f, 0x6f, 0x70, 0x22, 0x00, 0x42, 0x12, 0x5a,
	0x10, 0x6c, 0x69, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_misc_proto_service_server_proto_rawDescOnce sync.Once
	file_misc_proto_service_server_proto_rawDescData = file_misc_proto_service_server_proto_rawDesc
)

func file_misc_proto_service_server_proto_rawDescGZIP() []byte {
	file_misc_proto_service_server_proto_rawDescOnce.Do(func() {
		file_misc_proto_service_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_misc_proto_service_server_proto_rawDescData)
	})
	return file_misc_proto_service_server_proto_rawDescData
}

var file_misc_proto_service_server_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_misc_proto_service_server_proto_goTypes = []interface{}{
	(*Bridge)(nil),          // 0: proxy.Bridge
	(*Bridges)(nil),         // 1: proxy.Bridges
	(*Noop)(nil),            // 2: proxy.Noop
	(*LoginReq)(nil),        // 3: proxy.LoginReq
	(*StringMsg)(nil),       // 4: proxy.StringMsg
	(*BytesMsg)(nil),        // 5: proxy.BytesMsg
	(*PingReq)(nil),         // 6: proxy.PingReq
	(*PortScanReq)(nil),     // 7: proxy.PortScanReq
	(*ConnOut)(nil),         // 8: proxy.ConnOut
	(*ConnIn)(nil),          // 9: proxy.ConnIn
	(*RevProxyRequest)(nil), // 10: proxy.RevProxyRequest
	(*RevProxyConnIn)(nil),  // 11: proxy.RevProxyConnIn
	(*RevProxyConnOut)(nil), // 12: proxy.RevProxyConnOut
}
var file_misc_proto_service_server_proto_depIdxs = []int32{
	0,  // 0: proxy.Bridges.eps:type_name -> proxy.Bridge
	0,  // 1: proxy.ConnOut.bridge:type_name -> proxy.Bridge
	2,  // 2: proxy.NXProxy.Ver:input_type -> proxy.Noop
	8,  // 3: proxy.NXProxy.Proxy:input_type -> proxy.ConnOut
	8,  // 4: proxy.NXProxy.ReverseProxyListen:input_type -> proxy.ConnOut
	11, // 5: proxy.NXProxy.ReverseProxyWork:input_type -> proxy.RevProxyConnIn
	4,  // 6: proxy.NXProxy.Ping:input_type -> proxy.StringMsg
	4,  // 7: proxy.NXProxy.PortScan:input_type -> proxy.StringMsg
	4,  // 8: proxy.NXProxy.Nc:input_type -> proxy.StringMsg
	4,  // 9: proxy.NXProxy.SpeedTest:input_type -> proxy.StringMsg
	2,  // 10: proxy.NXProxy.KeepAlive:input_type -> proxy.Noop
	2,  // 11: proxy.NXProxy.GetConfigs:input_type -> proxy.Noop
	2,  // 12: proxy.NXProxy.StreamConfig:input_type -> proxy.Noop
	3,  // 13: proxy.NXProxy.Login:input_type -> proxy.LoginReq
	4,  // 14: proxy.NXProxy.Logout:input_type -> proxy.StringMsg
	2,  // 15: proxy.NXProxy.Ver:output_type -> proxy.Noop
	9,  // 16: proxy.NXProxy.Proxy:output_type -> proxy.ConnIn
	10, // 17: proxy.NXProxy.ReverseProxyListen:output_type -> proxy.RevProxyRequest
	12, // 18: proxy.NXProxy.ReverseProxyWork:output_type -> proxy.RevProxyConnOut
	4,  // 19: proxy.NXProxy.Ping:output_type -> proxy.StringMsg
	4,  // 20: proxy.NXProxy.PortScan:output_type -> proxy.StringMsg
	4,  // 21: proxy.NXProxy.Nc:output_type -> proxy.StringMsg
	5,  // 22: proxy.NXProxy.SpeedTest:output_type -> proxy.BytesMsg
	4,  // 23: proxy.NXProxy.KeepAlive:output_type -> proxy.StringMsg
	1,  // 24: proxy.NXProxy.GetConfigs:output_type -> proxy.Bridges
	1,  // 25: proxy.NXProxy.StreamConfig:output_type -> proxy.Bridges
	4,  // 26: proxy.NXProxy.Login:output_type -> proxy.StringMsg
	2,  // 27: proxy.NXProxy.Logout:output_type -> proxy.Noop
	15, // [15:28] is the sub-list for method output_type
	2,  // [2:15] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_misc_proto_service_server_proto_init() }
func file_misc_proto_service_server_proto_init() {
	if File_misc_proto_service_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_misc_proto_service_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bridge); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_service_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bridges); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_service_server_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Noop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_service_server_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_service_server_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StringMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_service_server_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BytesMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_service_server_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_service_server_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PortScanReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_service_server_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_service_server_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_service_server_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RevProxyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_service_server_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RevProxyConnIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_service_server_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RevProxyConnOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_misc_proto_service_server_proto_msgTypes[8].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_misc_proto_service_server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_misc_proto_service_server_proto_goTypes,
		DependencyIndexes: file_misc_proto_service_server_proto_depIdxs,
		MessageInfos:      file_misc_proto_service_server_proto_msgTypes,
	}.Build()
	File_misc_proto_service_server_proto = out.File
	file_misc_proto_service_server_proto_rawDesc = nil
	file_misc_proto_service_server_proto_goTypes = nil
	file_misc_proto_service_server_proto_depIdxs = nil
}
